version: '3.1'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - 9092:9092
    environment:
      # - ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_LISTENERS:EXTERNAL_SAME_HOST://0.0.0.0:9092
      # - KAFKA_ADVERTISED_LISTENERS:EXTERNAL_SAME_HOST
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,OUTSIDE://192.168.124.193:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper